<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="laser_visual"  default="true"/>
    <xacro:property name ="scan_radius" value="0.1" />
    <xacro:property name ="scan_length" value="0.06" />

    <link name="base_scan">
        <visual>
            <geometry>
                <cylinder radius="${scan_radius}" length="${scan_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision> 
            <geometry>
                <cylinder radius="${scan_radius}" length="${scan_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${2*scan_radius}" h="${2*scan_radius}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan"/>
        <origin xyz="0 0 ${base_height + scan_length/2 }" rpy="0 0 0"/>
    </joint>


    <gazebo reference="base_scan">
        <material>Gazebo/Orange</material>
        <sensor type="ray" name="lidar">
      <pose>0 0 0 0 0 0</pose>
      <visualize>$(arg laser_visual)</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>0.0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120</min>
          <max>3.5</max>
          <resolution>0.015</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
        <!-- name of the topic -->
        <remapping>~/out:=scan</remapping>
      </ros>
      <output_type>sensor_msgs/LaserScan</output_type>
      <frame_name>base_scan</frame_name>
    </plugin>
    </sensor>
    </gazebo>

</robot>